### ISSUE TITLE
build fail in the course due to outdated ruby version

### ISSUE THREAD

**Issue by Yemeni** [githubtraining/ci-travis#43]
## Bug Report

https://github.com/Yemeni/continuous-integration-travis/pull/3 as you can see here, it failed multiple times, so I updated ruby to 2.4.4, again failed due to incompatible bundles, then again updated ruby to 2.5 to finally have a successful build

**Comment by brianamarie** [comment]
Related, from Halp:

> A user opened this issue in our community forum indicating that the Travis CI tutorial is broken at the moment. https://travis-ci.community/t/tutorial-failing-first-step-could-not-find-bundler-1-16-3-required-by-your-gemfile-lock/10020

> You can see the breakage at https://travis-ci.com/github/Masber/continuous-integration-travis/builds/186822485#L277

> `Gemfile.lock`'s Bundler version does not match what's on the build image; I'm not yet entirely certain how or when the breakage was introduced. I'd be happy to discuss how we can fix it for our mutual users.
